<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateOrdersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable();
            $table->string('addr')->nullable();
            $table->string('phone')->nullable();
            $table->boolean('is_inside_area')->nullable();
            $table->string('payment_method')->default('COD');
            $table->float('sub_total')->nullable();
            $table->float('shipping_fee')->nullable();
            $table->float('total')->nullable();
            $table->boolean('is_paid')->default(false);
            $table->string('order_id')->nullable(); // unique order id (generated by the system)
            $table->string('status')->default('pending');
            
            $table->unsignedBigInteger('user_id')->nullable();
            $table->timestamps();

            $table
                ->foreign('user_id')
                ->references('id')
                ->on('users')
                ->onDelete('set null');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('orders');
    }
}
